### ISSUE TITLE
crashes ntr 

### ISSUE THREAD

**Issue by Khatrie** [Stary2001/InputRedirection#2] opened 2016-09-20 17:44 UTC
ntr now crashes upon running bootntr after starting input redirection. n3dsxl 11.1 newest version of luma and a9lh

**Comment by Stary2001** [comment] 2016-09-20 18:00
do you have the newest version of BootNTR with 11.1 firm support? can be found https://github.com/astronautlevel2/BootNTR/releases/tag/3.4 here

**Comment by jonwv** [comment] 2016-09-25 16:40
Input Redirection doesn't seem to work in 11.1 even with BootNTR 11.1 firm support. If you run input redirection.cia prior to running BootNTR, it sometimes causes BootNTR to fail to run. I've gotten two different errors, something along the lines of the kernalhax failing and then something along the lines of home menu version not supported. When it does seem to run properly and puts you back in the home menu, X + Y does not function. There are others experiencing just a crash when running input redirection, in the comments here https://www.reddit.com/r/3dshacks/comments/53jwzm/full_111_ntr_support/

BootNTR otherwise works perfectly fine on 11.1 if you do not run input redirection.

**Comment by Stary2001** [comment] 2016-09-25 17:43
I can't seem to reproduce this - just did 5 start inputredirection ntr/start bootntr/reboot cycles without any errors (x+y menu works fine). Are you on old3ds/2ds or new3ds?
edit: i'm on 11.1 with latest luma3ds, new3ds

**Comment by jonwv** [comment] 2016-09-25 20:39
Heh when I try to record it, everything starts working fine and I've tried several times and it's all working fine now. Khatrie are you still experiencing the issue?

**Comment by Stary2001** [comment] 2016-09-26 11:55
@Khatrie please reproduce or confirm this is not an inputredirection issue so this can be closed

**Comment by Stary2001** [comment] 2016-10-03 12:31
closing as no reply for a week and issue cannot reproduced..

**Closed as completed by Stary2001** 2016-10-03 12:31 UTC
